sudo: required
dist: trusty
language: python

before_install:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install shellcheck

install: pip install -r requirements.txt --upgrade

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

script:
  - ./pre-commit.sh
